# Generated by Django 3.0.6 on 2020-05-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('abbreviation', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_conversion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mealplanner.Fraction')),
                ('unit_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_from', to='mealplanner.Unit')),
                ('unit_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_to', to='mealplanner.Unit')),
            ],
        ),
    ]
