# Generated by Django 3.0.6 on 2020-05-27 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mealplanner.Ingredient')),
                ('ingredient_amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mealplanner.Fraction')),
                ('ingredient_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mealplanner.Unit')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='mealplanner.RecipeIngredient', to='mealplanner.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(to='mealplanner.Step'),
        ),
    ]
